language: cpp

compiler:
  - gcc

env:
  - GLIBCXX_DEBUG=1
  - NO_GLIBCXX_DEBUG=1

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++-dev libboost-all-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - rake test
